### ISSUE TITLE
IndexError and read_table error under Conda 4.8.3

### ISSUE THREAD

**Issue by drelo** [biobakery/graphlan#2]
I posted a comment on a similar issue I am having with hclust2 but here is my  issue with graphlan:

I am using Fedora 32 and conda 4.8.3, 

```
(expmpa) [andrespara@nagual MetaPhlAn]$ export2graphlan.py -i ab.txt -o out.txt -t ab.tree -a ab.annotated.txt
/export/home/andrespara/miniconda3/envs/expmpa/bin/hclust2.py:152: FutureWarning: read_table is deprecated, use read_csv instead.
  index_col = self.args.sname_row if self.args.sname_row > -1 else None
Traceback (most recent call last):
  File "/export/home/andrespara/miniconda3/envs/expmpa/bin/export2graphlan.py", line 770, in <module>
    main()
  File "/export/home/andrespara/miniconda3/envs/expmpa/bin/export2graphlan.py", line 512, in main
    lefse_input = DataMatrix(args.lefse_input, args)
  File "/export/home/andrespara/miniconda3/envs/expmpa/bin/hclust2.py", line 152, in __init__
    index_col = self.args.sname_row if self.args.sname_row > -1 else None
  File "/export/home/andrespara/miniconda3/envs/expmpa/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/export/home/andrespara/miniconda3/envs/expmpa/lib/python2.7/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/export/home/andrespara/miniconda3/envs/expmpa/lib/python2.7/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/export/home/andrespara/miniconda3/envs/expmpa/lib/python2.7/site-packages/pandas/io/parsers.py", line 2033, in read
    values = data.pop(self.index_col[i])
IndexError: list index out of range
```

I followed this steps to set conda channels https://bioconda.github.io/user/install.html#set-up-channels
I installed the export2graphlan in its own environment as follows:

```
(base) [andrespara@nagual MetaPhlAn]$ conda create --name expmpa -c bioconda export2graphlan
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /export/home/andrespara/miniconda3/envs/expmpa

  added / updated specs:
    - export2graphlan


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.1-py_0
  backports_abc      conda-forge/noarch::backports_abc-0.5-py_1
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.6.20-hecda079_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py27h8c360ce_1
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  enum34             conda-forge/linux-64::enum34-1.1.10-py27h8c360ce_1
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  export2graphlan    bioconda/noarch::export2graphlan-0.22-py_0
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  functools32        conda-forge/noarch::functools32-3.2.3.2-py_3
  futures            conda-forge/linux-64::futures-3.3.0-py27h8c360ce_1
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.65.0-h6f030ca_0
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_2
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_2
  hclust2            bioconda/linux-64::hclust2-0.99-py27_0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  jpeg               conda-forge/linux-64::jpeg-9d-h516909a_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.1.0-py27h9e3301b_1
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_5
  libblas            conda-forge/linux-64::libblas-3.8.0-17_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-17_openblas
  libclang           conda-forge/linux-64::libclang-9.0.1-default_hde54327_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  liblapack          conda-forge/linux-64::liblapack-3.8.0-17_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-he513fc3_1
  libopenblas        conda-forge/linux-64::libopenblas-0.3.10-h5ec1e0e_0
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_1
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxkbcommon       conda-forge/linux-64::libxkbcommon-0.10.0-he1b5a44_0
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  llvm-openmp        conda-forge/linux-64::llvm-openmp-10.0.0-hc9558a2_0
  matplotlib         conda-forge/linux-64::matplotlib-2.2.5-1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-2.2.5-py27h250f245_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  nspr               conda-forge/linux-64::nspr-4.26-he1b5a44_0
  nss                conda-forge/linux-64::nss-3.47-he751ad9_0
  numpy              conda-forge/linux-64::numpy-1.16.5-py27h95a1406_0
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_0
  pandas             conda-forge/linux-64::pandas-0.24.2-py27hb3f55d8_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pip                conda-forge/noarch::pip-20.1.1-pyh9f0ad1d_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pyqt               conda-forge/linux-64::pyqt-5.12.3-py27hcca6a23_1
  python             conda-forge/linux-64::python-2.7.15-h5a48372_1011_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-2.7-1_cp27mu
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  qt                 conda-forge/linux-64::qt-5.12.5-hd8c4c69_1
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  scipy              conda-forge/linux-64::scipy-1.2.1-py27h921218d_2
  setuptools         conda-forge/linux-64::setuptools-44.0.0-py27_0
  singledispatch     conda-forge/linux-64::singledispatch-3.4.0.3-py27_1000
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.32.3-hcee41ef_0
  subprocess32       conda-forge/linux-64::subprocess32-3.5.4-py27h516909a_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  tornado            conda-forge/linux-64::tornado-5.1.1-py27h14c3975_1000
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate expmpa
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

Any help would be appreciated!

**Comment by fbeghini** [comment]
Is `ab.txt` a table with merged MetaPhlAn profiles?

**Comment by drelo** [comment]
Yes, I just renamed the file before transferring to another place but it was obtained with this code `merge_metaphlan_tables.py metaphlan_output*.txt > output/merged_abundance_table.txt` 

Here it is 

[ab.txt](https://github.com/biobakery/graphlan/files/4870183/ab.txt)

**Comment by fbeghini** [comment]
See https://github.com/SegataLab/hclust2/issues/1
